# Project info
site_name: Startup Taxes
site_description: Making taxes easier and better for startups
site_author: Michael Feng
site_url: http://mifeng.github.io/startup-taxes

# Repository
repo_name: 'mifeng/startup-taxes'
repo_url: 'https://github.com/mifeng/startup-taxes'

# Copyright
copyright: 'Copyright &copy; 2017 Michael Feng'

# Theme
theme: 'material'
theme_dir: 'theme'

# Extra
extra:
  palette:
    primary: 'blue grey'
    accent: 'teal'

# Config
docs_dir: docs-edit

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

# Page tree
pages:
    - 'Intro': index.md
    - 'Problem': problem.md
    - 'Market size': market.md
    - 'Why now?': whynow.md
    - 'Product': product.md
    - 'Go-to-market': goto.md
    - 'Competitive landscape': landscape.md
    - 'Common objections': objections.md
    - 'Timeline': timeline.md
    
#    - About: about.md
#    - Disclaimer: disclaimer.md

  
